name: validate

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate:
    name: Validate on Node ${{ matrix.node }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    strategy:
      matrix:
        node: ["22.x", "24.x", "26.x"]
    runs-on: "ubuntu-latest"
    env:
      CI: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: labd/gh-actions-typescript/pnpm-install@e7a21fb56b52bf2d91616e34f0bc3f4f9a821b62 # main
        with:
          node-version: ${{ matrix.node }}

      - name: Check formatting and typing
        run: pnpm check

      - name: Run tests
        run: pnpm test:ci

      - name: Run build
        run: pnpm build

  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: release
    needs: validate
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: labd/gh-actions-typescript/pnpm-install@e7a21fb56b52bf2d91616e34f0bc3f4f9a821b62 # main
        with:
          node-version: 24.x

      - name: Run build
        run: pnpm build

      - name: Upgrade npm for trusted publishing
        run: npm i -g npm@11.12.1

      - name: Create and publish versions
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          pr-title: "Release new version"
          commit-message: "update version"
          publish-script: pnpm publish:ci
          version-script: pnpm publish:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
